experiment_name: alexnet_to_ae_conv5_animals_eval

# out pretrained cINN
pretrained_key: "cinn_alexnet_aae_conv5"

# the greybox one wants to analyze
GreyboxModel:
  split_idx: 12
  model: invariances.greybox.models.AlexNetClassifier
  subconfig:
    model: invariances.greybox.classifiers.AlexNet
    Model:
      pretrained: True