experiment_name: alexnet_to_ae_conv5_animals_eval

iterator: invariances.iterator.cinn_trainer.AutoencoderConcatTrainer
loss: iin.losses.iin.Loss #  only relevant for training, calculates the negative log-likelihood

# the greybox one wants to analyze
GreyboxModel:
  split_idx: 12
  model: invariances.greybox.models.AlexNetClassifier
  subconfig:
    Model:
      pretrained: True

# the autoencoder model for visualization
AutoencoderModel:
  pretrained_ae_key: "bigae_animals"

# the conditional INN
model: invariances.model.cinn.Dummy  # TODO: get rid of this
pretrained_model: invariances.model.cinn.ConditionalTransformer
pretrained_key: "cinn_alexnet_aae_conv5"

# other hyperparameters
base_learning_rate: 4.5e-06
batch_size: 16
num_steps: 250000
log_freq: 1000


datasets:
  train: autoencoders.data.Folder   # todo: this is a dummy, still neeed this in autoencoders
  validation: autoencoders.data.Folder

Folder:
  folder: "data/custom"
  size: 128

# fid-score calculation
fid:
  batch_size: 20
fid_stats:
  pre_calc_stat_path: /fid_stats/animals128