experiment_name: alexnet_to_ae_fc7_animals_eval

# the greybox one wants to analyze
GreyboxModel:
  split_idx: 21
  model: invariances.greybox.models.AlexNetClassifier
  subconfig:
    model: invariances.greybox.classifiers.AlexNet
    Model:
      pretrained: True

# the conditional INN
pretrained_key: "cinn_alexnet_aae_fc7"