experiment_name: alexnet_to_ae_fc6_animals

# the greybox one wants to analyze
GreyboxModel:
  split_idx: 18
  model: invariances.greybox.models.AlexNetClassifier
  subconfig:
    model: invariances.greybox.classifiers.AlexNet
    Model:
      pretrained: True

# the conditional INN
model: invariances.model.cinn.ConditionalTransformer
Transformer:
    hidden_depth: 2
    in_channels: 128
    mid_channels: 1024
    n_flows: 20
    conditioning_in_channels: 4096
    conditioning_spatial_size: 1
    embedder_down: 3
    activation: "none"
    conditioning_option: "none"
