datasets:
  train: autoencoders.data.AnimalFacesSharedTrain
  validation: autoencoders.data.AnimalFacesSharedTest
size: 128

iterator: invariances.iterator.cinn_trainer.AutoencoderConcatTrainer
loss: iin.losses.iin.Loss

# other hyperparameters
base_learning_rate: 4.5e-06
batch_size: 16
num_steps: 250000
log_freq: 1000

# the autoencoder model for visualization
AutoencoderModel:
  pretrained_ae_key: "bigae_animalfaces"

# fid-score calculation
fid:
  batch_size: 20
fid_stats:
  pre_calc_stat_path: /fid_stats/animalfaces128